NUMPY PACKAGE 

In [1]:
import numpy as np

In [2]:
simple_list=[6, 7, 9]
np.array(simple_list)

array([6, 7, 9])

In [4]:
arr=np.array([6, 7, 9])
arr

array([6, 7, 9])

In [7]:
np.arange(10,38)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])

In [9]:
np.arange(10,38,7)

array([10, 17, 24, 31])

In [10]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [15]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
np.linspace(0,15,4,dtype=int)

array([ 0,  5, 10, 15])

In [28]:
np.eye(6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [37]:
np.random.randn(4,6)

array([[-0.19632586, -0.08000258, -0.56010262,  0.05911347, -1.31616281,
         0.5802854 ],
       [ 0.15660639, -0.09355602, -1.24649631, -0.84014421, -0.67082967,
        -0.39193543],
       [-0.26326595,  0.22324051,  0.10089513, -2.9380885 ,  0.71628828,
         1.723148  ],
       [-0.86385385, -3.38637404,  1.85614186, -0.19097878,  0.47221028,
        -0.5991089 ]])

In [43]:
np.random.randint(0,10,15)

array([3, 2, 1, 9, 0, 1, 3, 9, 9, 3, 8, 4, 6, 4, 8])

|

CREATE AN ARRAY

In [44]:
import numpy as np